export const languages = [
  "English",
  "Assamese",
  "Bengali",
  "Gujarati",
  "Hindi",
  "Kannada",
  "Konkani",
  "Malayalam",
  "Marathi",
  "Nepali",
  "Odia",
  "Punjabi",
  "Sanskrit",
  "Tamil",
  "Telugu",
  "Urdu",
];

export const languageMapping: { [key: string]: string } = {
  English: "en",
  Assamese: "as",
  Bengali: "bn",
  Gujarati: "gu",
  Hindi: "hi",
  Kannada: "kn",
  Konkani: "kok",
  Malayalam: "ml",
  Marathi: "mr",
  Nepali: "ne",
  Odia: "or",
  Punjabi: "pa",
  Sanskrit: "sa",
  Tamil: "ta",
  Telugu: "te",
  Urdu: "ur",
};
